### ISSUE TITLE
Consider forking

### ISSUE THREAD

**Issue by altearius** [2x2xplz/json_visualizer#1]
Hello!

I appreciate you doing this!  I was also dismayed to find the original home of my JSON visualizer had ceased to be.  Fortunately, I had a backup of the code myself, which I've also put up on Github.

Rather than cloning the code from the internet archive, would you consider creating a fork of https://github.com/altearius/tools ?  Just in case I ever make changes to it, it would be nice to maintain a link between your copy and mine.

Thanks!

- Chris

**Comment by 2x2xplz** [comment]
Thanks so much Chris. Very happy to have the original source back! As you asked, I've created a new repo that is a fork of yours: https://github.com/2x2xplz/cntools. I hope you got my "beer fund" donations over the years!

**Comment by dermot-hardy** [comment]
It's hands down the best JSON visualizer on the internet.  I've been using [WayBack](https://web.archive.org/web/20200117222321/http://chris.photobooks.com/json/default.htm) since the site went down so it's great to find https://altearius.github.io/tools/json/index.html and https://2x2xplz.github.io/json_visualizer/default.htm.  Thank you.
